services:
  db:
    image: postgres:17
    container_name: szellit-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb/szellit_dump.sql:/docker-entrypoint-initdb.d/szellit_dump.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d szellit"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - szellit-network

  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    container_name: szellit-server
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      # Database connection override
      DB_HOST: db
    restart: always
    networks:
      - szellit-network

  client:
    build:
      context: ./client
      dockerfile: ../Dockerfile.client
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_CONTACT_RECEIVER: ${VITE_CONTACT_RECEIVER}
    container_name: szellit-client
    depends_on:
      - server
    ports:
      - "5173:5173"
    restart: always
    networks:
      - szellit-network

volumes:
  db_data:

networks:
  szellit-network:
    driver: bridge
